clone:
  depth: 1

options:
  docker: true

definitions:
  services:
    docker:
      memory: 2048

pipelines:
  default:
    - parallel:
        # build go app
        - step:
            name: go-test
            image: golang:1.15-alpine
            script:
              - |
                export CGO_ENABLED=0
                export GOOS=linux
                export GOARCH=amd64
              - apk update && apk add git make bash curl
              - |
                echo ${OZONE_CONFIG} | base64 -d  > config/config-ozone-run_test.json
              - make init
              - make devtools
              - make build
              - make test

        # lint and test the Vue.js app
        - step:
            name: web-lint-test
            image: node:dubnium-alpine
            # caches:
            #   - cache-web
            script:
              - |
                export FORCE_COLOR=1
                export NODE_DISABLE_COLORS=0
              - cd web/
              - yarn install --frozen-lockfile --non-interactive
              - yarn lint --no-fix
              - yarn test:unit:coverage

        # build docker image
        - step:
            name: docker-image-build
            caches:
              - docker
            script:
              - make build_image
              - docker images
